services:

  jiralert:
    build: .
    container_name: jiralert
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - 9097:9097
    volumes:
      - ~/.aws/:/root/.aws:ro