services:

  jiralert:
    build: .
    container_name: jiralert
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      APP_ENV: ${APP_ENV}
    ports:
      - 9097:9097
    volumes:
      - ~/.aws/:/root/.aws:ro