services:

  jiralert:
    build: .
    container_name: jiralert
    environment:
      JIRA_API_URL: ${JIRA_API_URL}
      JIRA_PROJECT: ${JIRA_PROJECT}
      AWS_PROFILE: ${AWS_PROFILE}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - 9097:9097
    volumes:
      - ~/.aws/:/root/.aws:ro