name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'master'
      destination:
        description: 'Where to save the Docker image: ecr or artifact'
        type: choice
        options:
          - ecr
          - artifact
        required: true
        default: 'ecr'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Extract repository name and version
        id: extract-info
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION=${GITHUB_REF_NAME}
          else
            VERSION=${{ github.event.inputs.branch || github.ref_name }}
          fi
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=${REPO_NAME}:${VERSION}
          DOCKERFILE_PATH=./Dockerfile
          echo "Building image: $IMAGE_NAME using Dockerfile at: $DOCKERFILE_PATH"
          docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .

  save-as-artifact:
    needs: build
    if: ${{ github.event.inputs.destination == 'artifact' }}
    uses: ./.github/workflows/push-image-to-artifact.yml
    with:
      artifact_name: ${IMAGE_NAME}

  push-to-ecr:
    needs: build
    if: ${{ github.event.inputs.destination == 'ecr' }}
    uses: ./.github/workflows/push-image-to-ecr.yml
    with:
      image_name: ${IMAGE_NAME}
