name: Default

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
    - name: Build
      uses: rogerluizpereira/shared-actions/.github/actions/docker-build@master
    - name: Push
      uses: rogerluizpereira/shared-actions/.github/actions/ecr-push@master
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}
        aws-account: ${{ vars.AWS_ACCOUNT_ID }}
        repository-name: ${{ steps.build.outputs.repo-name }}
        image-tag: ${{ steps.build.outputs.version }}
