name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: false
        default: 'master'     
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'prd'

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: rogerluizpereira/shared-actions/.github/actions/ecs-deploy@master
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}
        aws-account: ${{ vars.AWS_ACCOUNT_ID }}
        aws-ecs-cluster: ${{ vars.AWS_ECS_CLUSTER }}
        aws-ecs-service: ${{ vars.AWS_ECS_SERVICE }}
        version: ${{ inputs.version }}
        environment: ${{ inputs.environment }}