name: Deploy to ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'master'

jobs:

  deploy:
    runs-on: ubuntu-latest
    outputs:
      REPO_NAME: ${{ steps.extract-info.outputs.REPO_NAME }}
    steps:
      - name: Extract repository name and version
        id: extract-info
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      
      - name: Pull the image from ECR
        run: |
          docker pull ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ steps.extract-info.outputs.REPO_NAME }}:master
  
      - name: Push Docker image to ECR
        run: |
          ECR_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}
          echo "Tagging and pushing image to ECR: $ECR_URI"
          docker tag $ECR_URI:master $ECR_URI:latest
          docker push --all-tags $ECR_URI