name: Push Docker Image to ECR

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image to push'
        type: string
        required: true
    secrets:
      aws_secret_access_key:
        required: true
        
jobs:
  push-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          ECR_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}
          echo "Tagging and pushing image to ECR: $ECR_URI"
          docker tag ${{ inputs.image_name }} $ECR_URI
          docker push $ECR_URI